name: Transform-Html
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        type: choice
        default: 'info'
        options:
        - info
        - warning
        - debug

jobs:
  generate_issues:
    name: Transform-Html
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
        COMMIT_COMMENT: Generate html by beautifulsoup
        SCRIPT_MANAGER_API_CLIENT_ID: ${{ secrets.SCRIPT_MANAGER_API_CLIENT_ID }}
        SCRIPT_MANAGER_API_CLIENT_SECRET: ${{ secrets.SCRIPT_MANAGER_API_CLIENT_SECRET }}
        SCRIPT_MANAGER_API_ENDPOINT: ${{ secrets.SCRIPT_MANAGER_API_ENDPOINT }}
        MY_SCRIPT_NAME: 'manipulate_bookmeter_html'
        THIS_FUNCTION_NAME: 'Transform-Html'
    steps:

    # Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Get Python version
      run: python -V

    # https://stackoverflow.com/a/60942437
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y/%m/%d')" >>$GITHUB_OUTPUT

    - name: Print ls result
      id: ls
      run: ls

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Git setting
      run: |
        git config --local user.email "52403447+landmaster135@users.noreply.github.com"
        git config --local user.name "landmaster135"

    - name: ${{ env.COMMIT_COMMENT }} and Git add
      run: python "./src/manipulate_bookmeter_html/main.py"

    - name: Record log
      run: |
        curl '${{ env.SCRIPT_MANAGER_API_ENDPOINT }}?scriptname=${{ env.MY_SCRIPT_NAME }}&function-name=${{ env.THIS_FUNCTION_NAME }}' \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{"path": "/log", "method": "POST", "client_info": {"id": "${{ env.SCRIPT_MANAGER_API_CLIENT_ID }}", "secret": "${{ env.SCRIPT_MANAGER_API_CLIENT_SECRET }}"}}'

    - name: Git commit
      run: |
        git log -1
        git diff --cached --quiet || (git commit -m "${{ env.COMMIT_COMMENT }}" && git push origin main)
